src/Masa.Blazor/wwwroot/css/masa-extend-blazor.css

💄 style(block-text): ui in dark mode

---

src/Doc/Masa.Blazor.Doc.CLI/Commands/GenerateApiJsonCommand.cs
src/Doc/Masa.Blazor.Doc/Demos/Components/ErrorHandler/doc/index.en-US.md
src/Doc/Masa.Blazor.Doc/Demos/Components/ErrorHandler/doc/index.zh-CN.md
src/Doc/Masa.Blazor.Doc/Demos/Components/ErrorHandler/props/OnErrorHandleAsync.razor
src/Doc/Masa.Blazor.Doc/Demos/Components/ErrorHandler/props/onErrorHandleAsync.md
src/Doc/Masa.Blazor.Doc/Demos/Components/ErrorHandler/usage/index.md
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MErrorHandler.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MErrorHandler.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/demos.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/demos.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/docs.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/docs.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/menu.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/menu.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.zh-CN.json
src/Masa.Blazor/Components/ErrorHandler/MErrorHandler.cs
src/Masa.Blazor/wwwroot/css/masa-blazor.css
src/Masa.Blazor/wwwroot/css/masa-extend-blazor.css

Fix issues [368](https://github.com/BlazorComponent/MASA.Blazor/issues/368)  [369](https://github.com/BlazorComponent/MASA.Blazor/issues/369)

fix: Fix alert css and doc describe

---

src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSimpleCheckbox.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSimpleCheckbox.zh-CN.json
src/Masa.Blazor/Components/Checkbox/MSimpleCheckbox.cs
src/Masa.Blazor/Components/DataTable/MDataTable.cs
src/Masa.Blazor/Components/DataTable/MDataTableHeader.cs
src/Masa.Blazor/Components/Select/MSelectList.cs

Input event is the same in Vue as Blazor's ValueChanged.

♻ refactor(MSimpleCheckbox): Rename OnInput to ValueChanged

---

src/Doc/Masa.Blazor.Doc/Demos/Components/Editor/misc/Method.razor
src/Doc/Masa.Blazor.Doc/Demos/Components/Editor/usage/Basic.razor
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.zh-CN.json
src/Masa.Blazor/wwwroot/js/quill/quill-helper.js

style：adjust document style

---

src/Doc/Masa.Blazor.Doc/Demos/Components/Markdown/props/Counter.razor
src/Doc/Masa.Blazor.Doc/Demos/Components/Markdown/props/upload.md
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.zh-CN.json

fix：There is a problem with the counter in vdtor SV mode. The counter demonstrates using IR mode #386

doc(MMarkdown): Update demos

---

src/Masa.Blazor/Components/ErrorHandler/MErrorHandler.cs

fixed errorhandler loop show msg

fix: errorhandler loop show msg

---

src/Doc/Masa.Blazor.Doc/Demos/Components/Editor/misc/Method.razor
src/Masa.Blazor/wwwroot/js/quill/quill-helper.js

Uploading pictures is not allowed under read-only and disabled conditions

fix(editor)：upload pictures is not allowed under readonly and disabled

---

src/Doc/Masa.Blazor.Doc/Demos/Components/Presets/children/ImageCaptcha/props/TextFieldStyle.razor
src/Masa.Blazor/Components/TextField/MTextField.cs

resolve TextField input reback and ImageCaptcha component demo add ErrorMessage

fix (MTextField): fix TextField input reback bug

---

src/Doc/Masa.Blazor.Doc.WebAssembly/wwwroot/index.html
src/Doc/Masa.Blazor.Doc/Shared/BaseLayout.razor

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/420

fix(DocSearch): wasm add doc search

---

src/Masa.Blazor/Masa.Blazor.csproj
src/Masa.Blazor/Presets/Captcha/ImageCaptcha/CaptchaGenerator.cs

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/417

fix(PImageCaptcha): blazor wasm skiasharp error 

---

src/Masa.Blazor/Presets/Modal/ModalBase.razor.cs

🐛 fix(PModal): Set the default transition of ModalBase

---

src/Masa.Blazor/Components/RangeSlider/MRangeSlider.cs
src/Masa.Blazor/Components/Slider/MSlider.cs

https://github.com/BlazorComponent/MASA.Blazor/issues/434

fix(MSlider&MRangeSlider): fix mouse up event not trigger and add touch event for mobile

---

src/Masa.Blazor/Components/Autocomplete/MAutocomplete.cs
src/Masa.Blazor/Components/FileInput/MFileInput.cs
src/Masa.Blazor/Components/Select/MSelect.cs
src/Masa.Blazor/Components/TextField/MTextField.cs

🐛 fix(MSelect): the status of focus is incorrect

---

src/Doc/Masa.Blazor.Doc/Pages/Components.razor.cs
src/Doc/Masa.Blazor.Doc/Pages/styles.razor.cs
src/Doc/Masa.Blazor.Doc/Shared/MainLayout.razor
src/Doc/Masa.Blazor.Doc/Shared/MainLayout.razor.cs
src/Doc/Masa.Blazor.Doc/Utils/ExceptionExtensions.cs
src/Masa.Blazor/Components/ErrorHandler/MErrorHandler.cs

resolve [#438](https://github.com/BlazorComponent/MASA.Blazor/issues/438)

fix(MErrorHandler): fix 404 request loop error in webassembly mode

---

src/Doc/Masa.Blazor.Doc/Demos/Components/Alert/doc/index.en-US.md
src/Doc/Masa.Blazor.Doc/Demos/Components/Presets/children/Toast/doc/index.en-US.md
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MInput.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MInput.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MRangeSlider.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MRangeSlider.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSlider.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSlider.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MTextField.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MTextField.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MTextarea.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MTextarea.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.zh-CN.json

resolve https://github.com/BlazorComponent/MASA.Blazor/issues/439

doc(PToast): fix PToast english doc has garbled and Alert english doc has chinese

---

src/Doc/Masa.Blazor.Doc/Services/CrawlService.cs
src/Doc/Masa.Blazor.Doc/wwwroot/robots.txt

sitemap use https or http by request

fix(docsearch): sitemap use https or http by request

---

src/Doc/Masa.Blazor.Doc/Services/CrawlService.cs
src/Doc/Masa.Blazor.Doc/wwwroot/robots.txt

fix: sitemap use https scheme

---

src/Doc/Masa.Blazor.Doc.Models/Extensions/StringExtensions.cs
src/Doc/Masa.Blazor.Doc/Components/SectionContent.razor
src/Doc/Masa.Blazor.Doc/wwwroot/robots.txt

remove anchor space and remove robots sitemap double quotes

fix: remove anchor space and remove robots sitemap double quotes

---

src/Masa.Blazor/Components/TextField/MTextField.cs
src/Masa.Blazor/Presets/Toast/PToast.razor.cs

fix error when duration is null, fix textfield internal value delay when submit fast

fix(PToast&MTextField): fix error when duration is null and textfield internal value delay

---

src/Masa.Blazor/Components/TextField/MTextField.cs

Value use InternalValue.  InputValue as TempValue

fix: MTextField bind-value reset bug

---

src/Masa.Blazor/Components/Autocomplete/MAutocomplete.cs
src/Masa.Blazor/Components/Select/MSelect.cs

🆕 feat(MAutocomplete): AutoSelectFirst support and up/down keydown enhancement

---

src/Masa.Blazor/Components/Checkbox/MCheckbox.cs
src/Masa.Blazor/Components/Switch/MSwitch.cs

🐛 fix: OnChange not work in MSwitch and MCheckbox

---

src/Doc/Masa.Blazor.Doc/Shared/Toc.razor.cs
src/Masa.Blazor/Components/TextField/MTextField.cs

🐛 fix(MTextField): Autofocus not work in Dialog

---

src/Doc/Masa.Blazor.Doc/Demos/Components/Editor/props/UploadPicture.razor
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/components/components.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/meta/stylesandanimations/components.zh-CN.json
src/Masa.Blazor/wwwroot/js/quill/quill-helper.js

Move the upload token from body to head
#_[531]_

fix(edito)：upload token and migrate to head

---

src/Masa.Blazor/Components/Chip/MChip.cs

🐛 fix(Chip): Color should not act on content text

---

src/Masa.Blazor/Components/FileInput/MFileInput.cs
src/Masa.Blazor/Components/TextField/MTextField.cs

Reverts BlazorComponent/MASA.Blazor#553

fix(FileInput): value would be null after bluring

---

src/Masa.Blazor/Components/TextArea/MTextArea.cs

🐛 fix(Textarea): re-calculate input height when value updated

---

src/Masa.Blazor/Components/TextField/MTextField.cs

Fix the problem that input characters will be eaten. Temporary solution, the problem still exists and will be resolved at 0.6.

🐛 fix(TextField): do not update value if Inputting is true

---

src/Masa.Blazor/Components/Divider/MDivider.cs

🐛 fix(Divider): cannot dispaly in MRow

---

src/Doc/Masa.Blazor.Doc/Demos/Components/FormInputs/children/Form/misc/ValidationEnumerableWithValidationResult.razor

Reverts BlazorComponent/MASA.Blazor#741

Revert "Fix(form):fix form parseFormValidation"

---

src/Masa.Blazor/Components/BottomNavigation/MBottomNavigation.cs

🐛 fix(BottomNavigation): crashed when App is enable

---

src/Docs/Masa.Docs.Shared/Components/App/AppCode.razor
src/Docs/Masa.Docs.Shared/Components/App/AppCopyButton.razor
src/Docs/Masa.Docs.Shared/Components/Menus/MobileMenuList.razor
src/Docs/Masa.Docs.Shared/Components/MobileToolIcons.razor
src/Docs/Masa.Docs.Shared/Components/Search.razor
src/Docs/Masa.Docs.Shared/Components/Tabs.razor
src/Docs/Masa.Docs.Shared/Components/ToolIcons.razor
src/Docs/Masa.Docs.Shared/Services/AppService.cs
src/Docs/Masa.Docs.Shared/Shared/AppBar.razor
src/Docs/Masa.Docs.Shared/Shared/AppBarItems.razor
src/Docs/Masa.Docs.Shared/Shared/MainLayout.razor
src/Docs/Masa.Docs.Shared/Shared/NavigationDrawer.razor
src/Docs/Masa.Docs.Shared/Shared/Toc.razor
src/Docs/Masa.Docs.Shared/wwwroot/css/docs.css
src/Docs/Masa.Docs.Shared/wwwroot/locale/en-US.json
src/Docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json

- Add mobile nav
- Update AppBar
- Update GithubIssues from toc

docs(next): Add mobile nav

---

src/Masa.Blazor/Components/Footer/MFooter.cs
src/Masa.Blazor/Components/NavigationDrawer/MNavigationDrawer.cs
src/Masa.Blazor/Components/SystemBar/MSystemBar.cs

🐛 fix(App): throw when js invoked on pre-rendering

---

src/Docs/Masa.Blazor.Docs/Examples/components/item-groups/ActiveClass.razor
src/Docs/Masa.Blazor.Docs/Examples/components/item-groups/Mandatory.razor
src/Docs/Masa.Blazor.Docs/Examples/components/item-groups/Multiple.razor
src/Docs/Masa.Blazor.Docs/Examples/components/item-groups/Usage.razor

🎬 docs(item-group): update for inverting theme

---

src/Masa.Blazor/Popup/Components/Alert/Alert.razor
src/Masa.Blazor/Popup/Components/Alert/Alert.razor.cs

🐛 fix(PopupService-Alert): wrong type of Rounded

---

src/Docs/Masa.Blazor.Docs/Components/Examples/Usage.razor.cs
src/Docs/Masa.Blazor.Docs/Examples/components/range-sliders/Usage.razor.cs

🎬 docs(RangeSlider): Usage

---

src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/grids/en-US.md
src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/grids/zh-CN.md
src/Docs/Masa.Docs.Core/Components/RelatedPages/RelatedPage.razor

📝 docs(Grids): update the link

---

src/Docs/Masa.Blazor.Docs/Examples/components/app-bars/ElevateOnScroll.razor
src/Docs/Masa.Blazor.Docs/Examples/components/sliders/AppendTextField.razor

🎬 docs(Slider): add style

---

src/Docs/Masa.Blazor.Docs/ApiGenerator/ApiGenerator.cs
src/Docs/Masa.Blazor.Docs/Components/Api/ApiDatatable.razor
src/Docs/Masa.Docs.Shared/wwwroot/locale/en-US.json
src/Docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json

📝 docs(api-methods): add methods supports in API page

---

src/Docs/Masa.Blazor.Docs/Examples/styles-and-animations/overflow/Property.razor

📝 docs(Overflow): Update text and style

---

src/Masa.Blazor/Popup/Components/Confirm/Confirm.razor
src/Masa.Blazor/Popup/Components/Prompt/Prompt.razor

🐛 fix(PopupService): Confirm and Prompt Button position compatible

---

src/Docs/Masa.Docs.Core/Components/AppHeading.razor.cs
src/Docs/Masa.Docs.Shared/Shared/Toc.razor.cs
src/Docs/Masa.Docs.Shared/wwwroot/js/docs.js

🐛 fix(docs): NavigateTo should scroll to the top

---

src/Masa.Blazor/Components/Gridstack/MGridstack.razor.cs

feat(Gridstack): change Reload method to public

---

src/Masa.Blazor/Components/Menu/MMenu.cs
src/Masa.Blazor/Components/Select/MSelect.cs

refactor: move logic such as activatable and outside-click to JS 

---

src/Masa.Blazor/Components/Treeview/MTreeview.cs
src/Masa.Blazor/Components/Treeview/MTreeviewNode.cs

🐛 fix(Treeview): conflict between ActiveClass and Color

---

src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MCheckbox.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MCheckbox.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePicker.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePicker.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePickerDateTable.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePickerDateTable.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePickerMonthTable.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePickerMonthTable.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePickerTable.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MDatePickerTable.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MHover.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MHover.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSnackbar.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSnackbar.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSwitch.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MSwitch.zh-CN.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MTreeview.en-US.json
src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MTreeview.zh-CN.json
src/Test/Masa.Blazor.Test/Checkbox/MCheckboxTests.cs
src/Test/Masa.Blazor.Test/Switch/MSwitchTests.cs

Fix unit testing to support generic component type.
No issue reference;

tests: Unit tests fixing

---

src/Docs/Masa.Blazor.Docs/wwwroot/data/apis/common.json

📝 docs: api rounded description error

---

src/Masa.Blazor/Components/ProgressCircular/MProgressCircular.cs

🐛 fix(ProgressCircular): hex color code doesn't work

---

src/Docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/Examples.razor
src/Docs/Masa.Blazor.Docs/Pages/Components.razor.cs
src/Docs/Masa.Blazor.Docs/Shared/WireframeLayout.razor
src/Docs/Masa.Docs.Core/Extensions/StringExtensions.cs
src/Docs/Masa.Docs.Core/IJSComponentConfigurationExtensions.cs

🐛 fix(DOCS): source code link of wireframe example is incorrect

---

src/Docs/Masa.Blazor.Docs/Examples/components/selects/Light.razor
src/Masa.Blazor/Components/Gridstack/MGridstack.razor.cs
src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
src/Masa.Blazor/Components/Menu/MMenu.cs
src/Masa.Blazor/Components/Select/MSelect.cs
src/Masa.Blazor/Components/Tooltip/MTooltip.cs

feat(Menu): `Attach` supports

---

src/Masa.Blazor/Components/BottomNavigation/MBottomNavigation.cs

fix(BottomNavigation): InputValue should update the application's bottom

---

docs/Masa.Blazor.Docs/wwwroot/pages/features/internationalization/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/features/internationalization/zh-CN.md

📝 docs: add Support MasaI18n in MAUI Blazor project

---

docs/Masa.Blazor.Docs/Examples/components/application/DynamicallyModifyTheme.razor
docs/Masa.Blazor.Docs/Examples/components/data-tables/CRUDActions.razor
docs/Masa.Blazor.Docs/Examples/components/date-pickers/Multiple.razor
docs/Masa.Blazor.Docs/Examples/components/echarts/LiveUpdate.razor
docs/Masa.Blazor.Docs/wwwroot/data/nav.json
docs/Masa.Blazor.Docs/wwwroot/pages/components/echarts/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/echarts/zh-CN.md
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/zh-CN.md
docs/Masa.Docs.Core/Components/NavItemContent.razor
docs/Masa.Docs.Core/JsonConverters/NavItemsJsonConverter.cs
docs/Masa.Docs.Core/Models/DefaultItem.cs
docs/Masa.Docs.Core/Models/IDefaultItem.cs
docs/Masa.Docs.Core/Models/NavItem.cs
docs/Masa.Docs.Shared/wwwroot/js/docs.js

- resolves #896
- resolves #84

docs: examples update

---

src/Masa.Blazor/Components/Select/MSelect.cs

fix(MSelect):  component's `MenuProps` property unexposed `MaxWidth` property

---

src/Masa.Blazor/Components/Slider/MSlider.cs

fix(Slider): Ignored attempt to cancel a touchmove event with cancelabel=false

---

docs/Masa.Blazor.Docs/Examples/components/forms/ValidationEnumerableWithValidationResult.razor
docs/Masa.Blazor.Docs/ServiceCollectionExtensions.cs
docs/Masa.Blazor.Docs/wwwroot/pages/components/forms/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/forms/zh-CN.md

🎬 docs(Form): missing the ValidationResult demo

---

src/Masa.Blazor/Presets/Cron/Items/CronItem.razor
src/Masa.Blazor/Presets/Cron/Items/CronItem.razor.cs
src/Masa.Blazor/Presets/Cron/Models/CronItemDataModel.cs

Fix cron expression initialization

refactor(Cron): update expression initialization

---

docs/Masa.Docs.Shared/Pages/Index.razor

fix:home page navigation bar invisibe in the selected status

fix(docs): home page navigation bar would lose it's selected status

---

.github/workflows/wasm-dev.yml
.github/workflows/wasm-prd.yml
scirpts/sitemapgenerate.py

chore: add sitemap generate github workflow

---

docs/Masa.Blazor.Docs/wwwroot/data/apis/cards/MCard-en-US.json
docs/Masa.Blazor.Docs/wwwroot/data/apis/cards/MCard-zh-CN.json
docs/Masa.Blazor.Docs/wwwroot/data/apis/common.json

MCard->api-> [elevation page](https://docs.masastack.com/styles-and-animations/elevation)
this url is error, it will display "Sorry, there's nothing at this address."

📝 docs: Card api description error

---

src/Masa.Blazor/Components/Alert/MAlert.cs

fix(Alert): Fix the problem that the border of alert is right angle

---

src/Masa.Try.Server/Program.cs
src/Masa.Try.Shared/MasaTrySharedExtension.cs
src/Masa.Try.Shared/Pages/Index.razor.cs
src/Masa.Try.WebAssembly/Program.cs

修复Masa.Try.Server无法使用编译

---

src/Masa.Try.Shared/Pages/Index.razor.cs
src/Masa.Try.Shared/wwwroot/js/try.js

增加Masa 组件部分语法支持 增加Github文件自动获取

---

docs/Masa.Blazor.Docs/Examples/components/monaco-editor/EditorBasicOptions.razor
docs/Masa.Blazor.Docs/Examples/components/monaco-editor/ExposedColors.razor
docs/Masa.Blazor.Docs/Examples/components/monaco-editor/HardWrapping.razor
docs/Masa.Blazor.Docs/Examples/components/monaco-editor/Usage.razor

docs(Monaco): 显示高度未跟随父容器

---

src/Masa.Blazor/Components/FileInput/MFileInput.cs

🐛 fix(FileInput): string convert to IBrowserFile

---

src/Masa.Blazor/Components/Image/MImage.cs

🐛 fix(Image): src with parenthesis aren't recognized

---

docs/Masa.Docs.Core/Components/FrontMatter.razor
docs/Masa.Docs.Core/Extensions/StringExtensions.cs
docs/Masa.Docs.Core/_Imports.cs

feat(docs): add id to componet header

---

src/Masa.Try.Shared/Masa.Try.Shared.csproj

更新Razor编译版本修复泛型问题

---

src/Masa.Blazor/Components/Monaco/MMonacoEditor.razor.cs

修复Monaco未使用Height

---

docs/Masa.Docs.Shared/Pages/Index.razor
docs/Masa.Docs.Shared/Shared/Toc.razor
docs/Masa.Docs.Shared/Shared/Toc.razor.cs
docs/Masa.Docs.Shared/wwwroot/js/docs.js

https://user-images.githubusercontent.com/38368335/226389350-08453bed-5cab-4c56-bdcd-357f45014c71.mp4

fix:navigation bar will not follow scroll bar scroll

---

.github/workflows/doc-index.yml
.github/workflows/wasm-prd.yml
Masa.Blazor.Docs.sln
docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
docs/Masa.Docs.Indexing/AlgoliaOption.cs
docs/Masa.Docs.Indexing/Data/Hierarchy.cs
docs/Masa.Docs.Indexing/Data/Record.cs
docs/Masa.Docs.Indexing/Data/RecordRoot.cs
docs/Masa.Docs.Indexing/Data/RecordType.cs
docs/Masa.Docs.Indexing/Data/RecordVersion.cs
docs/Masa.Docs.Indexing/Data/Weight.cs
docs/Masa.Docs.Indexing/IIndexBuilder.cs
docs/Masa.Docs.Indexing/IndexHelper.cs
docs/Masa.Docs.Indexing/IndexHostedService.cs
docs/Masa.Docs.Indexing/Masa.Docs.Indexing.csproj
docs/Masa.Docs.Indexing/Program.cs
docs/Masa.Docs.Indexing/Properties/launchSettings.json
docs/Masa.Docs.Indexing/appsettings.json
docs/Masa.Docs.Indexing/readme.md
docs/Masa.Docs.Server/Pages/_Host.cshtml
docs/Masa.Docs.Shared/Components/Menus/LanguageMenu.razor
docs/Masa.Docs.Shared/Components/Search.razor
docs/Masa.Docs.Shared/Shared/AppBar.razor
docs/Masa.Docs.Shared/Shared/AppBarItems.razor
docs/Masa.Docs.Shared/Shared/BaseLayout.razor
docs/Masa.Docs.Shared/wwwroot/js/docs.js
docs/Masa.Docs.WebAssembly/wwwroot/index.html

support Full text retrieval (Algolia) 
#1125

feat(docs): support Full text retrieval (Algolia)

---

src/Masa.Blazor/Components/Autocomplete/MAutocomplete.cs
src/Masa.Blazor/Components/Select/MSelect.cs

🐛 fix(Autocomplete): The menu content obscures the input box in some cases

---

src/Masa.Blazor/Presets/PageTabs/PPageContainer.razor

resolves BlazorComponent/MASA.Blazor.Pro#179

🐛 fix(PageContainer): @page initializes multiple times in some cases

---

docs/Masa.Docs.Shared/Shared/BaseLayout.razor

the baseuri is endwith stash ,fix the match condition
#1125

fix: the baseuri switch fix

---

.github/workflows/doc-index-dev.yml
.github/workflows/wasm-dev.yml
.github/workflows/wasm-prd.yml
docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs

#1125 
- [feat(docs): set different language content to different index](https://github.com/BlazorComponent/MASA.Blazor/commit/5a849a7c0b423cb985a10a6799881b2650807ba8)
- [chore(docs): fix github workflow,as paramters,remove commet](https://github.com/BlazorComponent/MASA.Blazor/commit/a9f5a7639d796a7f97a866b3e9b2251c1f93e795)

feat(docs): set different language content to different index

---

docs/Masa.Docs.WebAssembly/wwwroot/index.html
src/Masa.Try.WebAssembly/wwwroot/index.html

solution from https://github.com/dotnet/aspnetcore/issues/39252

🐛 fix(PWA): WASM PWA integrity errors

---

.github/workflows/doc-index-dev.yml
.github/workflows/wasm-dev.yml
.github/workflows/wasm-prd.yml
.github/workflows/wasm-try.yml
docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
docs/Masa.Docs.Indexing/Masa.Docs.Indexing.csproj
docs/Masa.Docs.Indexing/Program.cs
docs/Masa.Docs.Indexing/Properties/launchSettings.json
docs/Masa.Docs.Indexing/appsettings.Development.json
docs/Masa.Docs.Indexing/appsettings.json

1. add env config file
2. log only using console and debug
3. add env debug log
4. change dotnet run folder to use config，and do not use lanchsetting.json

fix(docs): workflow debug message output

---

docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
docs/Masa.Docs.Indexing/Configurations/AlgoliaConfiguration.cs
docs/Masa.Docs.Indexing/Data/DescriptionYaml.cs
docs/Masa.Docs.Indexing/IIndexBuilder.cs
docs/Masa.Docs.Indexing/IndexHelper.cs
docs/Masa.Docs.Indexing/IndexHostedService.cs
docs/Masa.Docs.Indexing/Masa.Docs.Indexing.csproj
docs/Masa.Docs.Indexing/Program.cs

feat(docs): add parsing support for blazor componet document

---

docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
docs/Masa.Docs.Indexing/Data/DescriptionYaml.cs
docs/Masa.Docs.Indexing/IIndexBuilder.cs

1. add tag parsing
2. clear index before creation
#1152

fix(docs): index creating fixed

---

.github/workflows/doc-index-dev.yml
docs/Masa.Docs.Server/Program.cs
docs/Masa.Docs.Shared/Components/MobileToolIcons.razor
docs/Masa.Docs.Shared/Components/Search.razor
docs/Masa.Docs.Shared/Shared/AppBarItems.razor
docs/Masa.Docs.Shared/wwwroot/js/docs.js

feat(docs): algolia search on small screen support 
chore(docs): the workflow for index creation was changed to take place after the development document is published
fix(docs): the server project can not run directly from visual studio

feat(docs): algolia search on small screen support

---

docs/Masa.Docs.Indexing/Data/Hierarchy.cs
docs/Masa.Docs.Indexing/Data/Record.cs
docs/Masa.Docs.Indexing/Data/RecordRoot.cs
docs/Masa.Docs.Indexing/Data/Weight.cs

refactor(docs): using Newtonsoft.Json instead System.Text.Json.Serialization

refactor(docs): using Newtonsoft.Json

---

src/Masa.Blazor/Presets/EllipsisText/EllipsisText.razor.cs

fix:EllipsisText.razor component release issues

---

.github/workflows/doc-index-prd.yml
.github/workflows/wasm-prd.yml
Masa.Blazor.Docs.sln
docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
docs/Masa.Docs.Indexing/Configurations/AlgoliaConfiguration.cs

feat(docs): algolia index creation support relative url start with "/"
fix(docs): build error fix

algolia index creation support relative url start with "/"

---

src/Masa.Blazor/Components/Monaco/MMonacoEditor.razor.cs
src/Masa.Try.Shared/Pages/Index.razor

修复try的monaco高度超出限制

---

docs/Masa.Docs.Core/Components/AppLink.razor.cs
docs/Masa.Docs.Core/Extensions/StringExtensions.cs
docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
docs/Masa.Docs.Indexing/Configurations/AlgoliaConfiguration.cs
docs/Masa.Docs.Indexing/Parsers/MasaDocParser.cs
docs/Masa.Docs.Shared/Shared/Toc.razor.cs
docs/Masa.Docs.Shared/wwwroot/js/docs.js

it will suppport below pattern
- stack/abc
- stack/abc#anchor
- /stack/abc
- /stack/abc#anchor

feat(docs): support relative url on document site

---

src/Masa.Blazor/Components/DataTable/MDataTable.cs

🆕 feat(DataTable): click, dbclick and contextmenu supports on Row

---

docs/Masa.Docs.Core/Components/AppCodeGroup.razor
docs/Masa.Docs.Shared/wwwroot/css/docs.css
docs/Masa.Docs.Shared/wwwroot/js/docs.js

- resolves masastack/Masa.Docs#158
- resolves masastack/Masa.Docs#159

docs(blockquote): Support for multi line in blockquote and fileName in code in CodeGroup

---

src/Masa.Blazor/Components/Autocomplete/MAutocomplete.cs
src/Masa.Blazor/Components/Select/MSelectList.cs

related issue: masastack/MASA.PM#351

🐛 fix(Select): highlight error after AutoSelectFirst enable

---

src/Masa.Blazor/Components/DataTable/MDataTable.cs
src/Masa.Blazor/Components/DataTable/MDataTableMobileRow.cs
src/Masa.Blazor/Components/DataTable/MDataTableRow.cs

resolves #1245 
```razor 
<DataTable ItemClass="ItemClass"></DataTable>
@code {
private string ItemClass(TItem item) {
return item == xx ? "error lighten-5" : "";
}
}
```

🆕 feat(DataTable): Supports for `ItemClass` with `Func<TItem,string>`

---

src/Masa.Blazor/Components/Select/MSelect.cs

🐛 fix(Select): auto scroll to the active item when open at 1st time

---

src/Masa.Blazor/Components/Radio/MRadio.cs

🐛 fix(Radio): OnIcon and OffIcon don't work

---

docs/Masa.Docs.Shared/Pages/DocumentCompile.razor
docs/Masa.Docs.Shared/Pages/DocumentCompile.razor.cs
docs/Masa.Docs.Shared/Shared/CompileLayout.razor

docs: feat docs-compile

---

docs/Masa.Docs.Core/Components/AppCode.razor
docs/Masa.Docs.Server/Pages/_Host.cshtml
docs/Masa.Docs.Shared/wwwroot/css/docs.css
docs/Masa.Docs.Shared/wwwroot/prism/prism-material-dark-for-masa.css
docs/Masa.Docs.WebAssembly/wwwroot/index.html

resolves masastack/MASA.Docs#185

📝 docs: Update the UI of app code

---

docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json

chore: Update i18n resource file

---

src/Masa.Blazor/Components/TextField/MTextField.cs

🐛 fix(TextField): Label width should change when label changed

---

src/Masa.Blazor/Components/DataTable/MSimpleTable.cs

fix(DataTable): FixedRight style should be validated at the first render

---

docs/Masa.Blazor.Docs/Examples/components/popup-service/Snackbar.razor
src/Masa.Blazor/Popup/Components/Prompt/Prompt.razor

♻ refactor(Prompt): Use TextField instead of Textarea as the input box

---

docs/Masa.Blazor.Docs/wwwroot/pages/components/markdowns/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/markdowns/zh-CN.md

📝 docs(Markdown): Update docs

---

docs/Masa.Blazor.Docs/wwwroot/pages/components/selects/en-US.md
src/Masa.Blazor/Components/Select/MSelect.cs
src/Masa.Blazor/Components/Select/MSelectList.cs

🐛 fix(Select): TextColor doesn't work

---

src/Masa.Blazor/Components/Rating/MRating.cs

⚡ refactor(Rating): improves the performance

---

docs/Masa.Blazor.Docs/Examples/components/echarts/Dark.razor
docs/Masa.Blazor.Docs/Examples/components/echarts/HeightAndWidth.razor
docs/Masa.Blazor.Docs/Examples/components/echarts/IncludeFunctionsInOption.razor
docs/Masa.Blazor.Docs/Examples/components/echarts/Theme.razor
docs/Masa.Blazor.Docs/Examples/components/echarts/Usage.razor
docs/Masa.Blazor.Docs/wwwroot/pages/components/baidumaps/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/drag-zone/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/echarts/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/echarts/zh-CN.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/editors/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/markdown-parsers/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/markdowns/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/monaco-editor/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/syntax-highlights/en-US.md
src/Masa.Blazor/Components/ECharts/MECharts.razor.cs

🐛 fix(ECharts): support for multi functions or lambda in option

---

docs/Masa.Blazor.Docs/wwwroot/data/nav.json
src/Masa.Blazor/Components/DatePicker/MDatePicker.cs

🐛 fix(DatePicker): Exception throws when value change to MinValue

---

src/Masa.Blazor/Components/Select/MSelect.cs

🐛 fix(Select): MenuProps calculated only once

---

src/Masa.Blazor/Components/Stepper/MStepperContent.cs

🆕 feat(Stepper): support for lazy loading the DOM and `Eager` feature

---

src/Masa.Blazor/Components/Tabs/MTabsBar.cs

🐛 fix(Tabs): tags flash in some scenarios

---

docs/Masa.Blazor.Docs/Examples/components/app-bars/ToggleNavigationDrawers.razor
docs/Masa.Blazor.Docs/Examples/components/navigation-drawers/Bottom.razor
docs/Masa.Blazor.Docs/Examples/components/navigation-drawers/Mini.razor
docs/Masa.Blazor.Docs/Examples/components/navigation-drawers/Temporary.razor
docs/Masa.Blazor.Docs/Examples/features/breakpoints/Dialog.razor
docs/Masa.Blazor.Docs/Examples/features/breakpoints/Name.razor
docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/Base.razor
docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/Discord.razor
docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/Inbox.razor
docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/SideNavigation.razor
docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/Steam.razor
docs/Masa.Blazor.Docs/Examples/getting-started/wireframes/SystemBar.razor
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/zh-CN.md
docs/Masa.Docs.Core/Shared/INavDrawer.cs
docs/Masa.Docs.Shared/Components/Menus/MobileMenuList.razor
docs/Masa.Docs.Shared/Pages/AnnualService.razor
docs/Masa.Docs.Shared/Pages/Index.razor
docs/Masa.Docs.Shared/Shared/BaseLayout.razor
docs/Masa.Docs.Shared/Shared/DocLayout.razor
docs/Masa.Docs.Shared/Shared/NavDrawer.razor
docs/Masa.Docs.Shared/Shared/Settings.razor
src/Masa.Blazor/Components/App/MApp.cs
src/Masa.Blazor/Components/DataTable/MDataTable.cs
src/Masa.Blazor/Components/Descriptions/MDescriptions.razor.cs
src/Masa.Blazor/Components/NavigationDrawer/MNavigationDrawer.cs
src/Masa.Blazor/Components/SlideGroup/MSlideGroup.cs
src/Masa.Blazor/Services/Breakpoint.cs
src/Masa.Blazor/Services/BreakpointChangedEventArgs.cs

🐛 fix(NavigationDrawer): `Value=false` doesn't work

---

src/Masa.Blazor/Components/Pagination/MPagination.cs

fix(Pagination): Selected items don‘t show or exception in some scenarios

---

src/Masa.Blazor/Components/Monaco/MMonacoEditor.razor.cs

🆕 feat(Monaco): Expose the editor instance JS ref

---

src/Masa.Blazor/Presets/Modal/ModalBase.razor.cs

fix(Modal): should reset loading state if an exception occurs on confirm

---

docs/Masa.Blazor.Docs/wwwroot/pages/components/gridstack/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/gridstack/zh-CN.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/markdown-parsers/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/markdown-parsers/zh-CN.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/monaco-editor/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/monaco-editor/zh-CN.md

📝 docs(JSPorxy): add missing css references and package version

---

docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
docs/Masa.Docs.WebAssembly/wwwroot/service-worker.published.js
src/Masa.Try.Server/Pages/_Host.cshtml
src/Masa.Try.Shared/wwwroot/js/try.js
src/Masa.Try.WebAssembly/wwwroot/index.html

feat(Try): add some CSS  and JS references and update the source code URL in demo

---

src/Masa.Blazor/Popup/Components/Confirm/Confirm.razor
src/Masa.Blazor/Popup/Components/Confirm/Confirm.razor.cs
src/Masa.Blazor/Popup/Components/Confirm/ConfirmOptions.cs
src/Masa.Blazor/Popup/PopupServiceExtensions.cs

Usage:
```razor
@using Masa.Blazor.Popup
@inject IPopupService PopupService
<button @onclick="ShowPopup">Show popup</button>
@code {
private async Task ShowPopup()
{
await PopupService.ConfirmAsync(options =>
{
options.Title = "Title here";
options.ContentContent = builder => builder.AddMarkupContent(0, "<b>Content here</b>");
});
}
}
```

feat(Confirm): supports for RenderFragment content

---

src/Masa.Blazor/Components/Input/MInput.cs
src/Masa.Blazor/Popup/Components/Prompt/Prompt.razor
src/Masa.Blazor/Popup/Components/Prompt/Prompt.razor.cs
src/Masa.Blazor/Popup/Components/Prompt/PromptOptions.cs
src/Masa.Blazor/Popup/PopupServiceExtensions.cs

Usage:
```razor
@inject IPopupService PopupService
<MButton OnClick="ShowPrompt">Show prompt</MButton>
@code 
{
private async Task ShowPrompt() {
await PopupService.PromptAsync(
"Title",
"Enter \"identity\" in the input box below to confirm the operation",
val => val is not null && val.ToLower() == checkInput.ToLower() ? true : "Please enter 'identity' to confirm the operation");
}
}
```

feat(PopupService-Prompt): supports for custom rule to validate input value

---

src/Masa.Blazor/Components/DatePicker/MDatePicker.cs

🐛 fix(DatePicker): fa-IR localization error for title year

---

src/Masa.Blazor/Components/NavigationDrawer/MNavigationDrawer.cs

fix(NavDrawer): main left should change when mobile breakpoint is changed

---

src/Masa.Blazor/Presets/Modal/ModalActionEventArgs.cs
src/Masa.Blazor/Presets/Modal/ModalBase.razor.cs

🆕 feat(Modal): add FormContext to ModalActionEventArgs

---

README.md

Folder Path Changed Doc to Docs

Update folder path

---

docs/Masa.Docs.Core/Components/AppTooltipButton.razor
docs/Masa.Docs.Shared/Components/ThemeToggle.razor
docs/Masa.Docs.Shared/wwwroot/css/docs.css
docs/Masa.Docs.Shared/wwwroot/js/docs.js

docs(theme): toggle theme with a circle transition

---

src/Masa.Blazor/Components/Rating/MRating.cs

🐛 fix(Rating): missing type='button' on each item

---

src/Masa.Blazor/Components/Descriptions/DescriptionsGroupItem.cs
src/Masa.Blazor/Components/Descriptions/IDescriptionsItem.cs
src/Masa.Blazor/Components/Descriptions/MDescriptions.razor.cs
src/Masa.Blazor/Components/Descriptions/MDescriptionsItem.razor.cs

🐛 fix(Descriptions): i18n.T doesn't work when culture changing

---

src/Masa.Blazor/Presets/PageTabs/PageContainer/PPageContainer.razor
src/Masa.Blazor/Presets/PageTabs/PatternPath.cs

🐛 fix(PageContainer): Keep track of the order of path

---

docs/Masa.Blazor.Docs/Examples/components/progress-linear/Default.razor
docs/Masa.Blazor.Docs/Examples/components/progress-linear/Determinate.razor
src/Masa.Blazor/Components/ProgressLinear/MProgressLinear.cs

```diff
- <MProgressLinear Value="val" OnChange="v => val = v"></MProgressLinear>
+ <MProgressLinear @bind-Value="val"></MProgressLinear>
```

♻ refactor(ProgressLinear): use ValueChanged instead of OnChange

---

src/Masa.Blazor/Components/App/MApp.cs
src/Masa.Blazor/Components/AppBar/MAppBar.cs
src/Masa.Blazor/Components/Main/MMain.cs
src/Masa.Blazor/Components/NavigationDrawer/MNavigationDrawer.cs
src/Masa.Blazor/Components/Stepper/MStepper.cs
src/Masa.Blazor/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
src/Masa.Blazor/Masa.Blazor.csproj
src/Masa.Blazor/Services/Application.cs
src/Masa.Blazor/Services/MasaBlazor.cs
src/Masa.Blazor/Services/MasaBlazorOptions.cs
src/Masa.Blazor/Services/SSROptions.cs

fix: cannot work in prerendering state

---

src/Masa.Blazor/Components/Slider/MSliderBase.cs

🐛 fix(Slider): RTL error on mouse move

---

src/Masa.Blazor/Components/Image/ImageDimensions.cs
src/Masa.Blazor/Components/Image/MImage.cs
src/Masa.Blazor/Components/Image/SrcObject.cs
src/Masa.Blazor/Components/Responsive/MResponsive.cs

🆕 feat(Image): support for lazy loading util intersect with view

---

docs/Masa.Blazor.Docs/Examples/labs/watermark/RefreshWatermark.razor
docs/Masa.Blazor.Docs/Examples/labs/watermark/Usage.razor
docs/Masa.Blazor.Docs/wwwroot/data/nav.json
docs/Masa.Blazor.Docs/wwwroot/pages/labs/watermark/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/labs/watermark/zh-CN.md
src/Masa.Blazor/Components/Watermark/MWatermark.razor
src/Masa.Blazor/Components/Watermark/MWatermark.razor.cs
src/Masa.Blazor/wwwroot/css/masa-blazor.extend.css

add watermark

---

docs/Masa.Docs.Shared/App.razor

修复水印加载程序集失败

---

src/Masa.Blazor/Components/DataIterator/MDataIterator.cs
src/Masa.Blazor/Components/DataTable/MDataTable.cs

💥 feat(DataTable): add `OnItemExpand` and update some event type

---

src/Masa.Blazor/Components/Pagination/MPagination.cs

resolves https://github.com/masastack/MASA.Blazor.Pro/issues/201

🐛 fix(Pagination): failed to calculate the max buttons when in dialog

---

docs/Masa.Docs.Shared/Pages/Index.razor
src/Masa.Blazor/Components/AppBar/MAppBar.cs
src/Masa.Blazor/Components/BottomNavigation/MBottomNavigation.cs
src/Masa.Blazor/Components/DataFilter/PDataFilter.razor.cs
src/Masa.Blazor/Components/DigitalClock/MDigitalClock.razor.cs
src/Masa.Blazor/Components/DragZone/MDragZone.cs
src/Masa.Blazor/Components/Drawflow/Drag/MDrag.cs
src/Masa.Blazor/Components/Drawflow/MDrawflow.cs
src/Masa.Blazor/Components/ECharts/MECharts.razor.cs
src/Masa.Blazor/Components/Editor/MEditor.cs
src/Masa.Blazor/Components/Gridstack/MGridstack.razor.cs
src/Masa.Blazor/Components/Image/MImage.cs
src/Masa.Blazor/Components/Lazy/MLazy.razor.cs
src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
src/Masa.Blazor/Components/Markdown/MMarkdown.cs
src/Masa.Blazor/Components/Overlay/MOverlay.cs
src/Masa.Blazor/Components/Pagination/MPagination.cs
src/Masa.Blazor/Components/PullRefresh/MPullRefresh.razor.cs
src/Masa.Blazor/Components/Rating/MRating.cs
src/Masa.Blazor/Components/Stepper/MStepperContent.cs
src/Masa.Blazor/Components/Tabs/MTabs.cs
src/Masa.Blazor/Components/TextField/MTextField.cs
src/Masa.Blazor/Presets/EllipsisText/EllipsisText.razor.cs
src/Masa.Blazor/Services/Breakpoint/Breakpoint.cs

♻ refactor: catch all exception throwed in DisposeAsync

---

src/Masa.Blazor/wwwroot/js/Masa.Blazor.lib.module.js

⚰ refactor: remove unused JavaScript initializer

---

docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs

修复组件展开动态编译失败

---

src/Masa.Blazor/Components/SlideGroup/MSlideGroup.cs
src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor

🐛 fix(Tabs): wrong arrow when RTL

---

src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor
src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor.cs

🆕 feat(PageTabs): support for closing tabs by middle click

---

src/Masa.Blazor/Components/TextField/MTextField.cs

🆕 feat(TextField): stop propagation when number input is focused

---

src/Masa.Blazor/Components/Cascader/MCascader.cs
src/Masa.Blazor/Components/Cascader/MCascaderColumn.cs
src/Masa.Blazor/Components/Menu/MMenu.cs

🐛 fix(Cascader): RTL doesn't work

---

src/Masa.Blazor/Components/Xgplayer/MXgMusicPlayer.cs

get the ref of MXgplayer, then `xgPlayer.InvokeVoidAsync("play");`

🆕 feat(Xgplayer): Expose the JS.InvokeVoidAsync method

---

src/Masa.Blazor/Components/Cascader/MCascader.cs
src/Masa.Blazor/Components/Menu/MMenu.cs

🐛 fix(Menu): position error in RTL

---

src/Masa.Blazor/Components/DataTable/MDataTable.razor
src/Masa.Blazor/Mixins/Mobile/MobileProvider.cs

🐛 fix(Datatable): not render in SSR server

---

src/Masa.Blazor/Components/Markdown/MMarkdown.cs

resolve https://github.com/masastack/MASA.Blazor/issues/1077

🆕 feat(Markdown): add EventCallback OnAfter

---

src/Masa.Blazor/Components/Editor/MEditor.cs
src/Masa.Blazor/Components/Editor/MEditor.razor

refactor(Editor): merge code from BlazorComponent

---

src/Masa.Blazor/Components/DataTable/MSimpleTable.razor.cs

Revert "fix(SimpleTable): setting Width is ineffective (#1770)"

---

src/Masa.Blazor/Components/Dialog/MDialog.razor.cs

🐛 fix(Dialog): no need to invoke JS to delete element if not attached

---

docs/Masa.Blazor.Docs/Shared/PageTabsLayout.razor
src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor
src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor.cs
src/Masa.Blazor/Presets/PageTabs/TabOptions.cs

添加一个closeable选项到标签页组件的TabOptions中，当设置为false时，该页面标签不显示关闭按钮，通过右键菜单也无法关闭该页面。

feat: Add closeable option to TabOptions (#1807)

---

docs/Masa.Blazor.Docs/wwwroot/data/nav.json
src/Masa.Blazor/Components/DatePicker/DatePickerTable/MDatePickerDateTable.cs
src/Masa.Blazor/Components/DatePicker/DatePickerTable/MDatePickerTable.cs
src/Masa.Blazor/Components/DatePicker/MDatePicker.cs

🆕 feat(DatePicker): Add support for ShowWeek and CalendarWeekRule

---

docs/Masa.Blazor.Docs/Examples/components/infinite-scroll/ChildContent.razor
docs/Masa.Blazor.Docs/Examples/components/infinite-scroll/Color.razor
docs/Masa.Blazor.Docs/Examples/components/infinite-scroll/CustomContent.razor
docs/Masa.Blazor.Docs/Examples/components/infinite-scroll/Manual.razor
docs/Masa.Blazor.Docs/Examples/components/infinite-scroll/Usage.razor
docs/Masa.Blazor.Docs/Examples/components/infinite-scroll/VirtualScroller.razor
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/zh-CN.md
src/Masa.Blazor/Components/InfiniteScroll/MInfiniteScroll.razor
src/Masa.Blazor/Components/InfiniteScroll/MInfiniteScroll.razor.cs

refactor(InfiniteScroll): ElementReference type values are no longer supported

---

src/Masa.Blazor/Components/Rating/MRating.cs

🐛 fix(Rating): failed to click on half icon

---

src/Masa.Blazor/Components/AppBar/MAppBarNavIcon.cs
src/Masa.Blazor/Components/Button/MButton.cs

♻ refactor(AppBarNavIcon): to inherit from MButton in order to utilize all its props

---

docs/Masa.Blazor.Docs/Examples/components/lists/SubComponentProps.razor
docs/Masa.Blazor.Docs/Examples/components/lists/Usage/AdvanceUsage.razor
docs/Masa.Blazor.Docs/wwwroot/pages/components/lists/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/lists/zh-CN.md
src/Masa.Blazor/Components/Avatar/MAvatar.cs
src/Masa.Blazor/Components/List/MListItem.cs
src/Masa.Blazor/Components/List/MListItemAvatar.cs
src/Masa.Blazor/Services/MasaBlazorComponentTypeMapper.cs
src/Masa.Blazor/wwwroot/css/masa-blazor.css

```razor
<MListItem
Title="Title"
Subtitle="Subtitle"
PrependAvatar="http://..."
PrependIcon="mdi-abc"
AppendAvatar="http://..."
AppendIcon="mdi-abc">
</MListItem>
```

🆕 (ListItem): Add sub-component props to simplify usage

---

docs/Masa.Blazor.Docs/Examples/components/buttons/IconName.razor
docs/Masa.Blazor.Docs/wwwroot/pages/components/buttons/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/buttons/zh-CN.md
src/Masa.Blazor/Components/Button/MButton.cs
src/Masa.Blazor/wwwroot/css/masa-blazor.css

🆕 (Button): simplify the usage of icon buttons

---

src/Masa.Blazor/Components/SystemBar/MSystemBar.razor

🐛 fix(SystemBar): missing @attribtues

---

src/Masa.Blazor/Components/Carousel/MCarouselItem.cs

🐛 fix(CarouselItem): href doesn't work

---

src/Masa.Blazor/Components/NavigationDrawer/MNavigationDrawer.razor.cs

🐛 fix(NavigationDrawer): layout should change after the Permanent changed

---

docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/frequently-asked-questions/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/frequently-asked-questions/zh-CN.md

📝 docs(FAQ): Add 'Global click debounce'

---

src/Masa.Blazor/Presets/PageTabs/PageContainer/PPageContainer.razor.cs

🐛 (PageContainer): failed to cahce the dom

---

docs/Masa.Blazor.Docs/Examples/components/forms/ValidateComplexType.razor
src/Masa.Blazor/Components/Input/MInput.Validatable.cs

fix(Form): when using ObjectGraphDataAnnotationsValidator, error messages still exist when update value programmatically

---

src/Masa.Blazor/Components/Data/MData.cs

⚰ refactor(Data): remove the unused and unimplemented Locale property

---

src/Masa.Blazor/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
src/Masa.Blazor/I18n/I18n.cs
src/Masa.Blazor/I18n/I18nServiceCollectionExtensions.cs

🐛 fix: MasaBlazorOptions should be registered as Scoped by default

---

docs/Masa.Blazor.Docs/Examples/components/expansion-panels/SubComponents.razor
docs/Masa.Blazor.Docs/wwwroot/data/nav.json
docs/Masa.Blazor.Docs/wwwroot/pages/components/expansion-panels/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/expansion-panels/zh-CN.md
src/Masa.Blazor/Components/ExpansionPanels/MExpansionPanel.razor
src/Masa.Blazor/Components/ExpansionPanels/MExpansionPanel.razor.cs

before:
```razor
<MExpansionPanel>
<MExpansionPanelHeader>
Item
</MExpansionPanelHeader>
<MExpansionPanelContent>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
</MExpansionPanelContent>
</MExpansionPanel>
```
now you can:
```razor
<MExpansionPanel Title="Item"
Text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.">
</MExpansionPanel>
```

feat(ExpansionPanel): add the Title and Text props for rendering subcomponents

---

docs/Masa.Blazor.Docs/wwwroot/data/apis/chips/zh-CN.json

Update chips zh-CN.json

---

docs/Masa.Blazor.Docs/wwwroot/data/page-to-api.json

Add descriptions[ **MDescriptions** & **MDescriptionsItem** ]

update page-to-api.json 

---

src/Masa.Blazor/Components/Chip/MChip.razor

🐛 fix(Chip): Filter doesn't work

---

src/Masa.Blazor/wwwroot/js/vditor/vditor-helper.js

🐛 fix(Markdown): Unable to get pasted files or dragged files

---

src/Masa.Blazor/Components/Descriptions/MDescriptions.razor.cs

🐛 fix(Descriptions): may generate a empty row

---

docs/Masa.Blazor.Docs/Pages/PageStackTab3.razor
src/Masa.Blazor/Presets/PageStack/NavController/PageStackClearEventArgs.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackNavController.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackPageClosedEventArgs.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackPushEventArgs.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackReplaceEventArgs.cs
src/Masa.Blazor/Presets/PageStack/PPageStack.razor
src/Masa.Blazor/Presets/PageStack/PPageStack.razor.cs
src/Masa.Blazor/Presets/PageStack/PPageStackItem.razor
src/Masa.Blazor/Presets/PageStack/PPageStackItem.razor.cs
src/Masa.Blazor/Presets/PageStack/StackPageData.cs
src/Masa.Blazor/Presets/PageStack/StackPages.cs

🆕 feat(PageStack): add PageClosed event to PageStackNavController

---

docs/Masa.Blazor.Docs/Examples/labs/toggles/Menu.razor
docs/Masa.Blazor.Docs/Examples/labs/toggles/TData.razor
docs/Masa.Blazor.Docs/Examples/labs/toggles/Usage.razor
docs/Masa.Blazor.Docs/wwwroot/data/apis/toggles/MToggle-en-US.json
docs/Masa.Blazor.Docs/wwwroot/data/apis/toggles/MToggle-zh-CN.json
docs/Masa.Blazor.Docs/wwwroot/data/nav.json
docs/Masa.Blazor.Docs/wwwroot/pages/labs/toggles/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/labs/toggles/zh-CN.md
docs/Masa.Docs.Shared/Components/Menus/NotificationsMenu.razor
docs/Masa.Docs.Shared/Components/ThemeToggle.razor
docs/Masa.Docs.Shared/wwwroot/locale/en-US.json
docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json
src/Masa.Blazor.Docs.ApiGenerator/ApiGenerator.cs
src/Masa.Blazor/Components/Toggle/MToggle.cs

🆕 add the new component MToggle

---

src/Masa.Blazor/Components/DatePicker/MDatePicker.razor
src/Masa.Blazor/Components/DatePicker/MDatePickerYears.razor
src/Masa.Blazor/Components/DatePicker/MDatePickerYears.razor.cs

🐛 fix(DatePicker): Incorrect year value when Locale="fa-IR"

---

src/Masa.Blazor/Components/Data/MData.cs
src/Masa.Blazor/Components/DataTable/MDataTable.razor.cs

🐛 fix(DataTable): filter in header doesn't work

---

src/Masa.Blazor/Components/DataTable/MobileRow/MDataTableMobileRow.razor

🐛 fix(DataTable): CellClass doesn't work on mobile

---

src/Masa.Blazor/Components/ExpansionPanels/MExpansionPanel.razor
src/Masa.Blazor/Components/ExpansionPanels/MExpansionPanel.razor.cs
src/Masa.Blazor/Components/ItemGroup/MGroupItem.cs
src/Masa.Blazor/Components/ItemGroup/MGroupable.cs
src/Masa.Blazor/Components/ItemGroup/MGroupableBase.cs
src/Masa.Blazor/Components/ItemGroup/MItemGroupBase.cs

fix(ExpansionPanels): unexpected IsActive paramter; ActiveClass is not working

---

src/Masa.Blazor/Components/AppBar/MAppBarNavIcon.cs

🐛 fix(AppBarNavIcon): compatibility with IconName

---

docs/Masa.Blazor.Docs/wwwroot/pages/labs/drawflow/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/labs/drawflow/zh-CN.md
docs/Masa.Blazor.Docs/wwwroot/pages/resources/made-with-masa-blazor/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/resources/made-with-masa-blazor/zh-CN.md

📝 docs(Drawflow): update docs

---

src/Masa.Blazor/Components/Transition/Elements/IfTransitionElement.cs
src/Masa.Blazor/Components/Transition/Elements/ShowTransitionElement.cs
src/Masa.Blazor/Components/Transition/Elements/ToggleableTransitionElement.cs

🐛 fix(transition): Multiple constructors accepting all given argument types have been found in type

---

docs/Masa.Blazor.Docs/Components/Examples/Example.razor.cs
docs/Masa.Blazor.Docs/Masa.Blazor.Docs.csproj

解决组件下try编译失败

---

src/Masa.Blazor/Components/DigitalClock/MDigitalClock.razor
src/Masa.Blazor/Components/DigitalClock/MDigitalClock.razor.cs

feat(DigitalClock): add `HideDisallowedTimes` and support auto scroll to the adjacent time on first render

---

src/Masa.Blazor/Components/DataTable/Header/MDataTableHeaderBase.razor
src/Masa.Blazor/Components/DataTable/Header/MDataTableHeaderDesktop.razor
src/Masa.Blazor/Components/DataTable/MDataTable.razor
src/Masa.Blazor/Components/DataTable/MDataTable.razor.cs
src/Masa.Blazor/Components/DataTable/MobileRow/MDataTableMobileRow.razor

feat(DataTable): add support for displaying index column by `ShowSerialNumber`

---

src/Masa.Blazor/Components/Form/MForm.razor

🐛 fix(Form): validation fails after Model changed

---

src/Masa.Blazor/Components/Form/MForm.razor

🐛 fix(Form): @key must be unique

---

src/Masa.Blazor/Components/Slider/MSliderBase.razor

🐛fix(Slider): incorrect transform style settings

---

docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PageStackNavController-en-US.json
docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PageStackNavController-zh-CN.json
docs/Masa.Blazor.Docs/wwwroot/data/other-apis.json
docs/Masa.Blazor.Docs/wwwroot/pages/labs/page-stack/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/labs/page-stack/zh-CN.md

📝 docs(PageStack): update for the TabChanged event

---

docs/Masa.Blazor.Docs/Examples/components/text-fields/Number.razor
docs/Masa.Blazor.Docs/wwwroot/pages/components/text-fields/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/text-fields/zh-CN.md
src/Masa.Blazor/Components/Input/MInput.Validatable.cs
src/Masa.Blazor/Components/TextField/MTextField.razor.cs
src/Masa.Blazor/Components/TextField/TextFieldNumberProperty.cs

🆕 feat(TextField): add support for setting precision for number type

---

src/Masa.Blazor/Components/AppBar/MAppBarNavIcon.cs

🐛 fix(AppBarNavIcon): class generation error

---

src/Masa.Blazor/Presets/PageStack/NavController/PageStackNavController.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackPushEventArgs.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackReplaceEventArgs.cs
src/Masa.Blazor/Presets/PageStack/PPageStack.razor.cs

🆕feat(PageStack): add support for clearing stack on push or replace

---

docs/Masa.Blazor.Docs/wwwroot/data/apis/dialogs/MDialog-en-US.json
docs/Masa.Blazor.Docs/wwwroot/data/apis/dialogs/MDialog-zh-CN.json

补充 MDialog 的doc apis 包含 zh-cn和en-us
no issues
no code changed

component/dialog doc zh-cn&en-us

---

src/Masa.Blazor/Components/Dialog/MDialog.razor.cs

🆕 feat(Dialog): add DisableAutoFocus parameter

---

docs/Masa.Blazor.Docs/Examples/components/treeview/LoadChildren.razor
docs/Masa.Blazor.Docs/wwwroot/data/demo/users.json
src/Masa.Blazor/Components/Treeview/MTreeview.razor.cs

Fixes #312. This pull request addresses an important update to the Treeview component.  
**Changes Made:**
- Modified the Treeview implementation to allow the values of `Value`, `Open`, and `Active` to be `null`. This change enhances the flexibility of the component, accommodating scenarios where these properties may not have a defined value.
**Commit Summary:**
- `fix(Treeview): the value of Value, Open and Active can be null now`
This update is crucial for improving the usability of the Treeview component in various contexts, ensuring it can handle cases where these properties are intentionally left unset. 
Please review the changes and provide feedback. Thank you!

fix(Treeview): the value of Value, Open and Active can be null now

---

src/Masa.Blazor/Presets/PageStack/NavController/PageStackNavController.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackPopEventArgs.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackPushEventArgs.cs
src/Masa.Blazor/Presets/PageStack/PPageStack.razor.cs

feat(PageStack): pop and push events can now check if the stack is empty

---

src/Masa.Blazor/Presets/PageStack/NavController/PageStackNavController.cs
src/Masa.Blazor/Presets/PageStack/NavController/PageStackPushEventArgs.cs
src/Masa.Blazor/Presets/PageStack/PPageStack.razor.cs
src/Masa.Blazor/Presets/PageStack/StackPages.cs

🆕 feat(PageStack): support removing top pages on push

---

docs/Masa.Blazor.Docs/Pages/Components.razor.cs
docs/Masa.Blazor.Docs/Pages/PageStackPage1.razor
docs/Masa.Blazor.Docs/Pages/PageStackPage2.razor
docs/Masa.Blazor.Docs/Pages/PageStackPage3.razor
docs/Masa.Blazor.Docs/Pages/PageStackPage4.razor
docs/Masa.Blazor.Docs/Pages/PageStackTab1.razor
docs/Masa.Blazor.Docs/Pages/PageStackTab2.razor
docs/Masa.Blazor.Docs/Pages/PageStackTab3.razor
docs/Masa.Blazor.Docs/Shared/PageStackLayout.razor
docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PPageStack-en-US.json
docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PPageStack-zh-CN.json
docs/Masa.Blazor.Docs/wwwroot/data/page-to-api.json
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/getting-started/upgrade-guide/zh-CN.md
src/Masa.Blazor/Presets/PageStack/PPageStack.razor
src/Masa.Blazor/Presets/PageStack/PPageStack.razor.cs
src/Masa.Blazor/Presets/PageStack/PPageStackContainer.razor
src/Masa.Blazor/Presets/PageStack/PPageStackContainer.razor.cs
src/Masa.Blazor/Presets/PageStack/TabRecord.cs
src/Masa.Blazor/Presets/PageStack/TabRule.cs
src/Masa.Blazor/Presets/PageTabs/Abstract/PatternPathComponentBase.cs
src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor.cs
src/Masa.Blazor/Presets/PageTabs/PatternPath.cs

🆕 feat(PageStack): allow specific tabs to be non-persistent

---

docs/Masa.Blazor.Docs/wwwroot/pages/features/internationalization/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/features/internationalization/zh-CN.md
docs/Masa.Docs.Shared/Masa.Docs.Shared.csproj
src/Masa.Blazor/Components/I18n/MI18n.razor.cs
src/Masa.Blazor/I18n/I18nServiceCollectionExtensions.cs

feat(MI18n): force to update i18n value if invoked by event

---

src/Masa.Blazor/Components/TextField/MTextField.razor.cs

Add support for the timeonly and dateonly formats.

feat(TextField):Add support for the timeonly and dateonly formats.

---

src/Masa.Blazor/Components/Dialog/MDialog.razor.cs
src/Masa.Blazor/Components/Menu/MMenu.razor.cs
src/Masa.Blazor/Components/NavigationDrawer/MNavigationDrawer.razor.cs
src/Masa.Blazor/Mixins/Dependent/IDependent.cs

fix(Dialog): miss updates due to lazy dialog content not existing in dependencies

---

src/Masa.Blazor/Components/Pagination/MPagination.razor.cs

🐛 fix(Pagination): optimize logic for displaying pagination items

---

docs/Masa.Blazor.Docs/Pages/PageTabs4.razor
docs/Masa.Blazor.Docs/Shared/PageTabsLayout.razor
docs/Masa.Blazor.Docs/wwwroot/pages/components/page-tabs/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/page-tabs/zh-CN.md
src/Masa.Blazor/I18n/Locales/en-US.json
src/Masa.Blazor/I18n/Locales/zh-CN.json
src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor
src/Masa.Blazor/Presets/PageTabs/PPageTabs.razor.cs
src/Masa.Blazor/Presets/PageTabs/PageContainer/PPageContainer.razor.cs
src/Masa.Blazor/Presets/PageTabs/PatternPath.cs
src/Masa.Blazor/Presets/PageTabs/TabOptions.cs

🆕 feat(PageTabs): add support for fixed tabs

---

docs/Masa.Blazor.Docs/Examples/components/chips/InSelects.razor
docs/Masa.Blazor.Docs/Examples/components/combobox/Chips.razor
src/Masa.Blazor/Components/Select/MSelect.razor
src/Masa.Blazor/Components/Select/SelectSelectionProps.cs

🆕 feat(Combobox): supports select custom chip when using SelectionContent

---

src/Masa.Blazor/Services/ThemeVariables.cs

🐛 fix(Theme): ensure opacity values are formatted using InvariantCulture

---

docs/Masa.Blazor.Docs/wwwroot/data/notifications.json
docs/Masa.Blazor.Docs/wwwroot/pages/mobiles/page-stack/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/mobiles/page-stack/zh-CN.md
docs/Masa.Docs.Core/Services/AppService.cs
docs/Masa.Docs.Server/Pages/_Host.cshtml
docs/Masa.Docs.Shared/Shared/BaseLayout.razor.cs
docs/Masa.Docs.Shared/Shared/DocLayout.razor
docs/Masa.Docs.Shared/wwwroot/css/docs.css
docs/Masa.Docs.Shared/wwwroot/js/docs.js
docs/Masa.Docs.Shared/wwwroot/locale/en-US.json
docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json
docs/Masa.Docs.WebAssembly/wwwroot/index.html

feat(docs): add koala-chat widget

---

docs/Masa.Blazor.Docs/Examples/components/data-tables/Usage.razor
docs/Masa.Blazor.Docs/Examples/components/data-tables/ValueExpression.razor
docs/Masa.Blazor.Docs/wwwroot/pages/components/data-tables/en-US.md
docs/Masa.Blazor.Docs/wwwroot/pages/components/data-tables/zh-CN.md
src/Masa.Blazor/Components/Data/ItemValue.cs
src/Masa.Blazor/Components/DataTable/DataTableHeader.cs
src/Masa.Blazor/Components/DataTable/DataTableHeader`.cs
src/Masa.Blazor/Components/DataTable/Row/ItemColProps.cs

feat(DataTable): introduce ValueExpression for simpler headers creation

---

src/Masa.Blazor/Components/Form/MForm.razor.cs

🐛 (Form): prevent unnecessary ValueChanged calls
