masastack/MASA.Blazor

- src/Doc/Masa.Blazor.Doc/Shared/BaseLayout.razor.cs
- Fix the problem of returning null when reading i18n key does not exist [#327](https://github.com/BlazorComponent/MASA.Blazor/pull/327)
> fix(BaseLayout): the problem of returning null when reading i18n key does not exist

- src/Masa.Blazor/Components/TextArea/MTextArea.cs
- src/Masa.Blazor/Components/TextField/MTextField.cs
- src/Masa.Blazor/Masa.Blazor.csproj
when use bind-value in text field and input fast, the bind-value will not change
> fix: text field input fast bug

- src/Masa.Blazor/Components/Select/MSelect.cs
OnBlur in MSelect should not be inovked at the onblur, should be invoked when click-outside event invoked.
> 🐛 fix(MSelect): OnBlur should be invoked when click-outside event invoked

- src/Docs/Masa.Blazor.Docs/Examples/components/echarts/Dark.razor
- src/Docs/Masa.Blazor.Docs/Examples/components/echarts/Locale.razor
- src/Docs/Masa.Blazor.Docs/Examples/components/echarts/Theme.razor
- src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/echarts/en-US.md
- src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/echarts/zh-CN.md
- src/Docs/Masa.Docs.Shared/wwwroot/locale/en-US.json
- src/Docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json
- src/Masa.Blazor/Components/ECharts/MECharts.razor.cs
Now ECharts does not need to manually call `DisposeECharts` to update the theme, just the parameters `Light`, `Dark`, `Theme` or cascaded `IsDark`. Also resolved #246.
> 🚸 feat(ECharts): improve the way to update the theme

- src/Docs/Masa.Blazor.Docs/Examples/components/application/DynamicallyModifyTheme.razor
- src/Docs/Masa.Blazor.Docs/Masa.Blazor.Docs.csproj
- src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/application/en-US.md
- src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/application/zh-CN.md
- src/Masa.Blazor.NewDocs.sln
- src/Masa.Blazor/Components/App/MApp.cs
- src/Masa.Blazor/Services/MasaBlazor.cs
之前的行为：
在 `MApp` 组件初始化时，使用 `JS` 添加 `styles`，无法动态修改
修改后的行为：
在  `MApp` 组件内部添加内联CSS，即使预渲染状态下无法使用 `JS` ，也可以确保正确生成预配置样式
修改 `MasaBlazor` 服务的 `Theme ` 属性为可写，并添加 `Action` 通知 `MApp` 组件样式已修改，重新生成内联CSS
组件库的文档没有适配深色模式，我也不熟悉组件库文档站点，所以没有同步修改适配，还请见谅
Machine translation: 
previous behavior:
When the `MApp` component is initialized, `styles` are added with `JS` and cannot be modified dynamically
Modified behavior:
Adding inline CSS inside the `MApp` component ensures that preconfigured styles are generated correctly even if `JS` is not available in the pre-rendered state
Modify the `Theme` property of the `MasaBlazor` service to be writable, and add `Action` to notify the `MApp` component style has been modified and regenerate the inline CSS
The documentation of the component library does not adapt to dark …
> feat: Support for dynamic theme modification

- src/Masa.Blazor/Components/Carousel/MCarousel.cs
> 🐛 fix(Carousel): clicking on delimiter does not work

- docs/Masa.Blazor.Docs/Examples/components/application/DynamicallyModifyTheme.razor
- docs/Masa.Blazor.Docs/wwwroot/pages/components/application/en-US.md
- docs/Masa.Blazor.Docs/wwwroot/pages/components/application/zh-CN.md
- src/Masa.Blazor/Services/MasaBlazor.cs
已按照如下说明修改代码：
1. MasaBlazor.Theme 仍然是只读的。
2. MasaBlazor类下搞一个 public 的方法 ToggleTheme，把Theme的set的内容移入进去。
3. 主题的设置应该再 AddMasaBlazor 时就确定下来，不应该修改，MasaBlazor.Theme.Themes.Light.Primary = color 不应该支持。
> refactor: change the way to toggle theme

- src/Masa.Blazor/Components/App/MApp.cs
because the `Dark` parameter is conflict with the `MasaBlazor.Theme.Dark`
> ♻ refactor(App): Dark theme can only be set through `AddMasaBlazor`

- docs/Masa.Docs.Server/Properties/launchSettings.json
- docs/Masa.Docs.Shared/Shared/Toc.razor.cs
- docs/Masa.Docs.Shared/wwwroot/js/docs.js
1. search document in same page
2. search use link to another page(it is some thing like )
3. use same config support http and https
> fix(docs): search result support scroll to anchor

- docs/Masa.Docs.Core/Components/AppCodeGroup.razor
resolves masastack/MASA.Docs#148
> 🐛 fix(AppCodeGroup): use `text-none` css for the tab content

- docs/Masa.Docs.Shared/Shared/BaseLayout.razor
- src/Masa.Blazor/Components/ErrorHandler/MErrorHandler.cs
It's useful when you don't want to show the error content and popup at the same time.
> 🆕 feat(ErrorHandler): Add `DisablePopupIfErrorContentRender` parameter

- src/Masa.Blazor/Components/ECharts/MECharts.razor.cs
Supported usage:
```cs
var option = new {
renderItem = @"
...
";
}
```
> 🆕 feat(ECharts): support for verbatim text of function string

- src/Masa.Blazor/Components/DateTimePicker/Views/PDateTimePickerViewBase.cs
> 🐛 fix(DateTimePicker): should not set seconds if UseSeconds is false

- src/Masa.Blazor/Components/DataIterator/MDataIterator.cs
`EventCallback<(TItem Item, bool Selected)>` failed to compile when SDK is net6.0 or net7.1.00.
> 🐛 fix(Datatable): compatible with net6.0

- src/Masa.Blazor/Components/Dialog/MDialog.cs
- src/Masa.Blazor/Components/Menu/MMenu.cs
- src/Masa.Blazor/Components/Tooltip/MTooltip.cs
Using `Permenant` parameter in Dialog/Menu/Tooltip components can prevent the failure of the page from popping up after a jump. Usually need to use this parameter on a layout component.
> 🆕 feat(pop-up): support for persistence of pop-up windows when using SSR

- src/Masa.Blazor/Components/DataTable/MSimpleTable.razor.cs
> 🐛 fix(SimpleTable): setting `Width` is ineffective

- src/Masa.Blazor/Components/Drawflow/MDrawflow.cs
因为当_drawflowProxy = await DrawflowJSModule.Init(ElementReference.GetSelector()!, _interopHandleReference, Mode);执行后,页面相关dom元素才会被渲染以及事件发生挂钩对接,若当有基础dataflow的json数据,这时候是无法初始化的,增加初始json数据参数以及loadData的event callback,协助初始化,不需要在first render的方法内进行delay.....等待相关dom渲染完成后再初始化控件的json数据..
> add init data and loadData event callback to be init

- docs/Masa.Blazor.Docs/Examples/components/text-fields/PasswordInput.razor
- src/Masa.Blazor/Components/Autocomplete/MAutocomplete.cs
- src/Masa.Blazor/Components/FileInput/MFileInput.cs
- src/Masa.Blazor/Components/Input/MInput.cs
- src/Masa.Blazor/Components/RangeSlider/MRangeSlider.cs
- src/Masa.Blazor/Components/Select/MSelect.cs
- src/Masa.Blazor/Components/Slider/MSliderBase.cs
- src/Masa.Blazor/Components/TextArea/MTextArea.cs
- src/Masa.Blazor/Components/TextField/MTextField.cs
- src/Masa.Blazor/Mixins/Selectable/MSelectable.cs
- src/Masa.Blazor/_Imports.cs
Now supported:
```razor
<MTextField Value="val1"
ValueChanged="ValueChanged1"
UpdateOnChange
TValue="string">
</MTextField>
<MTextField Value="val2"
ValueChanged="ValueChanged2"
TValue="string">
</MTextField>
@code {
private string val1;
private string val2;
private void ValueChanged1(string input)
{
if (double.TryParse(input, out var result))
{
val1 = result.ToString("0.00");
}
}
private void ValueChanged2(string input)
{
val2 = input.Trim(';');
}
}
```
> 🐛 fix(TextField): failed to modify the Value in ValueChanged

- src/Masa.Blazor/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
- src/Masa.Blazor/Services/MasaBlazor.cs
For WebAssembly and MAUI Hybrid, it is more appropriate to register MasaBlazor as a singleton.
> 🆕 feat: support for setting the lifetime of MasaBlazor service

- src/Masa.Blazor/Components/Dialog/DialogContentContext.cs
- src/Masa.Blazor/Components/Dialog/MDialog.razor
- src/Masa.Blazor/Components/Dialog/MDialog.razor.cs
OutcomeContent which provides DialogContentContext similar to ChildContent allows accessing the OnClose method within the context.
Previously, it was necessary to use an additional variable in the dialog content to close the dialog:
```razor
<MDialog @bind-Value="dialog">
<ActivatorContent>
<MButton @attribtues="@context.Attrs">BUTTON</MButton>
</ActivatorContent>
<ChildContent>
<p>content here...</p>
<MButton OnClick="CloseDialog">Close</MButton>
</ChildContent>
</MDialog>
@code {
private bool dialog;
private void CloseDialog() {
dialog = false;
}
}
```
Now you can:
```razor
<MDialog>
<ActivatorContent>
<MButton @attribtues="@context.Attrs">BUTTON</MButton>
</ActivatorContent>
<OutcomeContent>
<p>content here...</p>
<MButton OnClick="@context.Close">Close</MButton>
</OutcomeContent> …
```
> 🆕 feat(Dialog): add OutcomeContent with a DialogContentContext

- src/Masa.Blazor/Presets/EnqueuedSnackbars/PEnqueuedSnackbars.razor
- src/Masa.Blazor/Presets/EnqueuedSnackbars/PEnqueuedSnackbars.razor.cs
- src/Masa.Blazor/wwwroot/css/masa-blazor.extend.css
do not obscure components used for layout， such as AppBar and NavigationBottom.
> 🚸 feat(EnqueuedSnackbars): do not obscure components used for layout

- .github/workflows/wasm-prd.yml
- Masa.Blazor.sln
- docs/Masa.Docs.WebAssembly/wwwroot/index.html
- docs/Masa.Docs.WebAssembly/wwwroot/service-worker.published.js
When you update a method name in masa-blazor.js and redeploy the application, it might still call the old method due to Masa.Blazor.wasm using cached data. This can lead to an error message saying "Could not find 'new-method'". Therefore, it's important not to cache Blazor.boot.json and Masa.Blazor.wasm. The masa-blazor.js file is also cached, but you can modify it by changing the script reference in index.html, for example, by adding a version number like masa-blazor.js?versions=v1.6.0.
After redeployment, make sure to check if index.html has changed and avoid caching it as well. Testing has shown that caching of masa-blazor.js should be avoided too; otherwise, errors may occur due to mismatches between the hash of the new blazor.boot.json related to masa-blazor.js and its cached …
> 📝 (PWA): cache issue when change the function name in masa-blazor.js

- docs/Masa.Blazor.Docs/wwwroot/pages/components/dividers/zh-CN.md
- docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json
> # 合并分隔线与分割线两种翻译

- src/Masa.Blazor/Components/Button/MButton.razor.cs
- src/Masa.Blazor/Components/Card/MCard.razor.cs
- src/Masa.Blazor/Core/MasaComponentBase.cs
> fix(Button): exception thrown in click event wasn't being caught by the error handler

- docs/Masa.Blazor.Docs/Shared/PageStackLayout.razor
- src/Masa.Blazor/Presets/PageStack/NavController/PageStackNavController.cs
- src/Masa.Blazor/Presets/PageStack/NavController/PageStackTabChangedEventArgs.cs
- src/Masa.Blazor/Presets/PageStack/PPageStack.razor.cs
> 🆕 feat(PageStack): add support for current active tab change event

- src/Masa.Blazor/Components/Carousel/MCarousel.razor
- src/Masa.Blazor/Components/Carousel/MCarouselItem.cs
- src/Masa.Blazor/I18n/EmbeddedLocales.cs
> 🐛 fix(CarouselItem): the root tag should be `a` when Href is not null

- src/Masa.Blazor/Components/TextField/MTextField.razor.cs
and add the `UpdateValueImmediatelyAsync` public method for user to invoking by code.
> 🐛 fix(TextField): ensure getting the latest value in OnEnter event

- src/Masa.Blazor/Components/Sortable/MSortable.razor
- src/Masa.Blazor/Components/Sortable/MSortableProvider.cs
- src/Masa.Blazor/Components/Sortable/MSortableProviderBase.cs
When the items change, they should not be rendered in the order of the items. Now, after the items are updated, the UI order should be updated through js-interop based on the `Order` value during the next rendering.
> fix(Sortable): re-sort by `Order` through js-interop when items changed

- docs/Masa.Blazor.Docs/Examples/components/tooltips/Alignment.razor
- docs/Masa.Blazor.Docs/Examples/components/tooltips/Usage.razor
- docs/Masa.Blazor.Docs/Examples/components/tooltips/Visibility.razor
- docs/Masa.Blazor.Docs/wwwroot/pages/components/tooltips/en-US.md
- docs/Masa.Blazor.Docs/wwwroot/pages/components/tooltips/zh-CN.md
- src/Masa.Blazor/Components/Tooltip/MTooltip.razor
- src/Masa.Blazor/Components/Tooltip/MTooltip.razor.cs
> 🆕 feat(Tooltip): add `Text` parameter to simplify the use of displaying text

- src/Masa.Blazor/Components/Tooltip/MTooltip.razor.cs
> feat(Tooltip): make the Top as the default position to show tooltip

- docs/Masa.Blazor.Docs/Pages/PageStackPage3.razor
- src/Masa.Blazor/Presets/PageStack/PPageStack.razor.cs
简单来说就是history.go调用和内部pages维护堆栈的执行顺序没按预期发生。现在改为，popstate里执行维护堆栈的逻辑，就确保了先执行history.go调用跳转。
> 🐛 fix(PageStack): GoBackToPageAndReplace has subtle issues

- docs/Masa.Blazor.Docs/Examples/components/cascaders/BindList.razor
- docs/Masa.Blazor.Docs/Examples/components/cascaders/Delimiter.razor
- docs/Masa.Blazor.Docs/Examples/components/cascaders/LoadChildren.razor
- docs/Masa.Blazor.Docs/wwwroot/pages/components/cascaders/en-US.md
- docs/Masa.Blazor.Docs/wwwroot/pages/components/cascaders/zh-CN.md
- src/Masa.Blazor.Playground/Pages/Index.razor
- src/Masa.Blazor/Components/Cascader/ICascader.cs
- src/Masa.Blazor/Components/Cascader/MCascader.razor
- src/Masa.Blazor/Components/Cascader/MCascader.razor.cs
- src/Masa.Blazor/Components/Cascader/MCascaderColumn.razor.cs
- src/Masa.Blazor/Components/Select/MSelect.razor.cs
> 🆕 feat(Cascader): support binding value for `List<TItemValue>` type

- src/Masa.Blazor/Components/DataTable/MDataTable.razor
> 🐛 fix(DataTable): ensure group is open by default when not cached

- src/Masa.Blazor/Components/NavigationDrawer/MNavigationDrawer.razor.cs
> 🐛 fix(NavigationDrawer): disable touching to expand when Bottom set

- src/Masa.Blazor/Presets/PageTabs/PageContainer/PPageContainer.razor.cs
Fixes #2393 
This pull request refactors the event binding logic in the `PPageContainer` class to improve maintainability and reduce redundancy. The changes include introducing a new helper method for event binding, removing duplicate event subscriptions, and ensuring events are only bound once.
* Added a new private field `_eventBound` to track whether events have already been bound, preventing duplicate bindings. (`src/Masa.Blazor/Presets/PageTabs/PageContainer/PPageContainer.razor.cs`, [src/Masa.Blazor/Presets/PageTabs/PageContainer/PPageContainer.razor.csR49](diffhunk://#diff-219ed87e56ce913949a40a43721895389c311c7febca04c2022b75c48b964cb9R49))
* Introduced a helper method `BindEvents(PPageTabs? component)` to centralize event subscription logic, ensuring it is reusable and concise. …
> fix(PageTabs): refactor event binding for PageTabs to improve init logic

- docs/Masa.Blazor.Docs/Examples/components/tabs/DesktopTabs.razor
- docs/Masa.Blazor.Docs/Examples/components/tabs/DynamicHeight.razor
- docs/Masa.Blazor.Docs/Examples/components/tabs/DynamicTabs.razor
- docs/Masa.Blazor.Docs/Examples/components/tabs/Grow.razor
- docs/Masa.Blazor.Docs/Examples/components/tabs/IconAndText.razor
- docs/Masa.Blazor.Docs/Examples/components/tabs/OverflowToMenu.razor
- docs/Masa.Blazor.Docs/Examples/components/tabs/TabItems.razor
- src/Masa.Blazor/Components/Tabs/MTabs.razor
- src/Masa.Blazor/Components/Window/MWindow.razor.cs
> fix(tabs): touch swipe on tab-items doesn't update the tab value

- src/Masa.Blazor/Components/Markdown/MMarkdown.cs
> 🐛 fix(vditor): avoid clearing classes set by vditor when setting class

- docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PPageStack-en-US.json
- docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PPageStack-zh-CN.json
- docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PStackPageBar-en-US.json
- docs/Masa.Blazor.Docs/wwwroot/data/apis/page-stack/PStackPageBar-zh-CN.json
- docs/Masa.Blazor.Docs/wwwroot/data/page-to-api.json
- docs/Masa.Blazor.Docs/wwwroot/pages/mobiles/page-stack/en-US.md
- docs/Masa.Blazor.Docs/wwwroot/pages/mobiles/page-stack/zh-CN.md
- src/Masa.Blazor.Docs.ApiGenerator/ApiGenerator.cs
- src/Masa.Blazor.Docs.ComponentApiGenerator/ComponentApiGenerator.cs
- src/Masa.Blazor.MobileComponents/Presets/PageStack/PPageStack.razor
- src/Masa.Blazor.MobileComponents/Presets/PageStack/PPageStack.razor.cs
- src/Masa.Blazor.MobileComponents/Presets/PageStack/PPageStackItem.razor
- src/Masa.Blazor.MobileComponents/Presets/PageStack/PPageStackItem.razor.cs
- src/Masa.Blazor.MobileComponents/Presets/PageStack/PPageStackLink.razor
- src/Masa.Blazor.MobileComponents/Presets/PageStack/PStackPageBar.cs
- src/Masa.Blazor.MobileComponents/Presets/PageStack/PStackPageBase.cs
- src/Masa.Blazor.MobileComponents/Presets/PageStack/TabbedPage.cs
New:
- **PStackPageBar**: This replaces the old PStackPageBarInit and no longer requires a RerenderKey to notify the bar to re-render.
- `AppBarAlwaysVisible` parameter, which defaults to `true`, meaning the App bar will be displayed on every stack page. When set to `false`, only the stack pages marked with the PStackPageBar component will show the App bar.
> feat(PageStack): make stack page bar configurable to enhance UI diversity

- src/Masa.Blazor/Presets/EnqueuedSnackbars/PEnqueuedSnackbars.razor.cs
> 🐛 fix(EnqueuedSnackbars): remove unnecessary semaphore release for duplicate messages

- src/Masa.Blazor/Components/Dialog/MDialog.razor
- src/Masa.Blazor/Components/Dialog/MDialog.razor.cs
- src/Masa.Blazor/Components/ExpansionPanels/MExpansionPanelContent.razor
- src/Masa.Blazor/Components/ExpansionPanels/MExpansionPanelContent.razor.cs
- src/Masa.Blazor/Components/List/MListGroup.razor
- src/Masa.Blazor/Components/List/MListGroup.razor.cs
- src/Masa.Blazor/Components/Menu/MMenu.razor
- src/Masa.Blazor/Components/Menu/MMenu.razor.cs
- src/Masa.Blazor/Components/Stepper/MStepperContent.razor
- src/Masa.Blazor/Components/Stepper/MStepperContent.razor.cs
- src/Masa.Blazor/Components/Tooltip/MTooltip.razor
- src/Masa.Blazor/Components/Tooltip/MTooltip.razor.cs
- src/Masa.Blazor/Components/Window/MWindowItem.razor
- src/Masa.Blazor/Components/Window/MWindowItem.razor.cs
Previously, a version added the functionality of not rendering components with an "active/inactive" status unless they were activated, implemented through the ShouldRender component. Now, it appears that there are still some scenarios where "always renderable" is needed. This pull request introduces a new parameter named `ShouldRenderWhenInactive` that allows manually disabling the aforementioned functionality.
Related issue: #2390
> feat: add ShouldRenderWhenInactive parameter to allow rendering when inactive
